
services:
  - type: web
    name: lecture-schedule-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 1
